from .ir import Instruction, Module, Value


C_TYPES = {"i32": "int32_t", "f32": "float", "f64": "double", "bool": "bool"}


class CGenerator:
    def __init__(self):
        self.next_loop = 0
        self.next_temp = 0

    def temporary(self, dtype: str, expression: str, indent: int) -> tuple[str, str]:
        name = f"myrk_t_{self.next_temp}"
        self.next_temp += 1
        return f"{'    ' * indent}{C_TYPES[dtype]} {name} = {expression};", name

    def value(self, item: Value, indent: int) -> tuple[list[str], str]:
        if item.op == "constant":
            if item.dtype == "bool":
                return [], "true" if item.data else "false"
            if item.dtype == "f32":
                return [], f"{item.data}f"
            return [], str(item.data)
        if item.op == "variable":
            return [], item.data
        if item.op == "call":
            lines = []
            args = []
            for arg in item.args:
                prelude, rendered = self.value(arg, indent)
                lines.extend(prelude)
                assignment, name = self.temporary(arg.dtype, rendered, indent)
                lines.append(assignment)
                args.append(name)
            assignment, name = self.temporary(item.dtype,
                                              f"myrk_f_{item.data}({', '.join(args)})", indent)
            lines.append(assignment)
            return lines, name
        if item.op == "unary":
            lines, arg = self.value(item.args[0], indent)
            assignment, name = self.temporary(item.dtype, f"({item.data}{arg})", indent)
            return lines + [assignment], name
        if item.op == "binary":
            left_lines, left = self.value(item.args[0], indent)
            left_assignment, left = self.temporary(item.args[0].dtype, left, indent)
            right_lines, right = self.value(item.args[1], indent)
            right_assignment, right = self.temporary(item.args[1].dtype, right, indent)
            lines = left_lines + [left_assignment] + right_lines + [right_assignment]
            if item.data in ("/", "%") and item.args[0].dtype == "i32":
                helper = "div" if item.data == "/" else "mod"
                expression = f"myrk_{helper}_i32({left}, {right})"
            else:
                expression = f"({left} {item.data} {right})"
            assignment, name = self.temporary(item.dtype, expression, indent)
            return lines + [assignment], name
        raise AssertionError(item.op)

    def statement(self, item: Instruction, indent: int) -> list[str]:
        pad = "    " * indent
        if item.op == "declare":
            cname, dtype = item.data
            lines, value = self.value(item.args[0], indent)
            return lines + [f"{pad}{C_TYPES[dtype]} {cname} = {value};"]
        if item.op == "assign":
            lines, value = self.value(item.args[0], indent)
            return lines + [f"{pad}{item.data} = {value};"]
        if item.op == "return":
            lines, value = self.value(item.args[0], indent)
            return lines + [f"{pad}return {value};"]
        if item.op == "print":
            value = item.args[0]
            lines, rendered = self.value(value, indent)
            fmt = {"i32": '"%d\\n"', "f32": '"%.9g\\n"',
                   "f64": '"%.17g\\n"', "bool": '"%s\\n"'}[value.dtype]
            if value.dtype == "i32":
                rendered = f"(int)({rendered})"
            elif value.dtype == "f32":
                rendered = f"(double)({rendered})"
            elif value.dtype == "bool":
                rendered = f"({rendered}) ? \"true\" : \"false\""
            return lines + [f"{pad}printf({fmt}, {rendered});"]
        if item.op == "for":
            loop_id = self.next_loop
            self.next_loop += 1
            start, end, body = item.args
            start_lines, start_value = self.value(start, indent + 1)
            end_lines, end_value = self.value(end, indent + 1)
            lines = [f"{pad}{{"] + start_lines + [
                     f"{pad}    int32_t myrk_start_{loop_id} = {start_value};"] + end_lines + [
                     f"{pad}    int32_t myrk_end_{loop_id} = {end_value};",
                     f"{pad}    for (int32_t {item.data} = myrk_start_{loop_id}; "
                     f"{item.data} < myrk_end_{loop_id}; ++{item.data}) {{"]
            for child in body:
                lines.extend(self.statement(child, indent + 2))
            lines.extend((f"{pad}    }}", f"{pad}}}"))
            return lines
        raise AssertionError(item.op)

    def generate(self, module: Module) -> str:
        lines = ["// Generated by Myrk 0.1.0; do not edit.",
                 "#include <stdbool.h>", "#include <stdint.h>",
                 "#include <stdio.h>", "#include <stdlib.h>",
                 "#include <limits.h>",
                 "static int32_t myrk_div_i32(int32_t a, int32_t b) {",
                 "    if (b == 0 || (a == INT32_MIN && b == -1)) {",
                 '        fputs("Myrk runtime error: invalid i32 division\\n", stderr);',
                 "        exit(70);",
                 "    }",
                 "    return a / b;",
                 "}",
                 "static int32_t myrk_mod_i32(int32_t a, int32_t b) {",
                 "    if (b == 0 || (a == INT32_MIN && b == -1)) {",
                 '        fputs("Myrk runtime error: invalid i32 modulo\\n", stderr);',
                 "        exit(70);",
                 "    }",
                 "    return a % b;",
                 "}"]
        for procedure in module.procedures:
            params = ", ".join(f"{C_TYPES[dtype]} {name}" for name, dtype in procedure.params) or "void"
            lines.append(f"static {C_TYPES[procedure.result]} myrk_f_{procedure.name}({params});")
        for procedure in module.procedures:
            params = ", ".join(f"{C_TYPES[dtype]} {name}" for name, dtype in procedure.params) or "void"
            lines.append(f"static {C_TYPES[procedure.result]} myrk_f_{procedure.name}({params}) {{")
            for statement in procedure.body:
                lines.extend(self.statement(statement, 1))
            lines.append("}")
        lines.append("int main(void) { return (int)myrk_f_main(); }")
        return "\n".join(lines) + "\n"


def generate(module: Module) -> str:
    return CGenerator().generate(module)
